### PR TITLE
fix: enable the new forked Work API in member agent

### PR DESCRIPTION
**Pull request by michaelawyu**
### Description of your changes

This PR fixes an issue where the new forked Work API is not even enabled in member agent.

I have:

- [x] Run `make reviewable` to ensure this PR is ready for review.

### How has this code been tested

N/A

### Special notes for your reviewer

N/A

### CODE REVIEW

**Review by ryanzhang-oss — APPROVED** [review]
were the work CRDs not generated before?

**Comment by ryanzhang-oss** [comment]
The work related integration test failed

**Comment by michaelawyu** [comment]
Seems to be a flaky test on the work controller side. Will address in a separate PR.

**Comment by michaelawyu** [comment]
Hi Ryan! The CRDs have been generated; it's just that the symbolic links in charts are not created.

**Comment by michaelawyu** [comment]
The flakiness needs to be addressed later I assume. The unit tests and the E2E tests failed once respectively.

**Pull request merged**
